### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by AleIV** [InfinityZ25/SurvivalUniverse#3]
1. En Chunks y en City se puede agarrar las cosas que están en los armor stands, cancelar eso y que solo pueda el que tenga permiso en la respectiva zona.
2. El daño de enderpearl no existe cuando tienes Pvp desactivado, hacer que siempre exista ese daño.
3. Las explosiones NUNCA deben romper bloques en Chunks ni City, PERO hay una excepción que hay que agregar; Solo en city la TNT puede romper, SOLO la TNT.
4. El agua y la lava se puede poner en City y En Chunks, cancelar eso y permitirlo solo si tiene permiso dependiendo de la zona.
5. El daño a entidades cancelado en Chunks es un hecho, pero debe estar la excepción que si exista daño a jugadores, porq esto hace inmunes a los jugadores en Chunks.
6. Las campfires pueden ser encendidas con flechas de fuego, cancelar eso a menos de que sea la flecha de alguien con permiso en la zona.

**Comment by InfinityZ25** [comment]
Issues 2 is fixed now

**Comment by InfinityZ25** [comment]
Issue 4, 5, fixed

**Comment by InfinityZ25** [comment]
Issue #3 Fixed

**Comment by InfinityZ25** [comment]
Issue 1 fixed

**Comment by InfinityZ25** [comment]
Issue 1 feature added. Done and completed.
