### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by AleIV** [InfinityZ25/SurvivalUniverse#4]
1. Crear /home que te lleve a tu lugar de spawn, ósea tu cama, pero te haga la transición de TP especial.

2. Cuando un jugador muere a causa de un creeper eléctrico dropea la cabeza del jugador muerto 

3. Modificar, simplificar e implementar el randomtp y tus mecanismos de “survivalAle” a “survivalUnviverse”

**Comment by InfinityZ25** [comment]
Creeper feature added.

**Comment by InfinityZ25** [comment]
All features, and related
