### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by AleIV** [InfinityZ25/SurvivalUniverse#6]
1. Helper no debería poder interactuar ni hacer nada en chunks de la gente dentro de city, tampoco debería poder poner agua ni lava.
2. Si alguien apunta a un bloque intentando tirar una enderpearl no deja, que si deje y cuidado con no dejarlo interactuar gracias a eso.

**Comment by InfinityZ25** [comment]
Working on this now

**Comment by InfinityZ25** [comment]
Potentially fixed already

**Comment by InfinityZ25** [comment]
Commit 786a840  should fix it

**Comment by InfinityZ25** [comment]
Fixed by 3c456a9
